-- NOTE:
-- This migration was generated by Drizzle after introspecting an existing database.
-- It is intentionally a NO-OP for NexaCare because the production/dev database already has the base schema.
--
-- For a brand-new empty database, use:
--   npm run db:push
-- to create the schema directly from `shared/schema.ts`.
SELECT 1;